# Generated by Django 5.0.4 on 2024-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsettings',
            name='machine_type',
            field=models.CharField(default='Standard_B1s', help_text='All posible machine types can be found here, copy them EXACTLY AS WRITTEN: https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2024_03_01.models.hardwareprofile?view=azure-python#keyword-only-parameters', max_length=256),
        ),
        migrations.AddField(
            model_name='evaluationsettings',
            name='memory',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='evaluationsettings',
            name='cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evaluationsettings',
            name='time_limit',
            field=models.FloatField(default=60),
        ),
    ]
