# Generated by Django 5.0.4 on 2024-06-28 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='container',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='filepath',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
