# Generated by Django 5.0.4 on 2024-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evaluationsettings_machine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_downloadable',
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='container',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='filepath',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
