# Generated by Django 5.0.4 on 2024-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_storagelocation_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'None'), ('s', 'Seconds'), ('min', 'Minutes'), ('h', 'Hours'), ('KB', 'Kilobytes'), ('MB', 'Megabytes'), ('GB', 'Gigabytes')], default='', max_length=4),
        ),
    ]
