# Generated by Django 5.0.4 on 2024-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100)),
                ("submission_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
