# Generated by Django 5.0.4 on 2024-05-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_id',
            new_name='id',
        ),
    ]
