# Generated by Django 5.0.4 on 2024-06-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_result_score'),
        ('api', '0004_problemcategory_example_submission_url'),
    ]

    operations = [
    ]
