# Generated by Django 5.0.4 on 2024-05-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_submission_id_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
