# Generated by Django 5.0.4 on 2024-05-16 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_submission_submission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField()),
                ('time_limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BenchmarkInstance',
            fields=[
                ('storagelocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.storagelocation')),
            ],
            bases=('api.storagelocation',),
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('storagelocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.storagelocation')),
            ],
            bases=('api.storagelocation',),
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('storagelocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.storagelocation')),
            ],
            bases=('api.storagelocation',),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=512)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SpecifiedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.CharField(max_length=512)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problemcategory')),
                ('evualuation_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.evaluationsettings')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specifiedproblem'),
        ),
        migrations.CreateModel(
            name='BenchmarkSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specifiedproblem')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.benchmarkinstance')),
            ],
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='simulator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simulator'),
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.validator'),
        ),
    ]
