# Generated by Django 5.0.4 on 2024-05-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_storagelocation_evaluationsettings_problemcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationSettings',
            new_name='EvaluationSetting',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
