# Generated by Django 5.0.4 on 2024-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifiedproblem',
            name='style',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
