# Generated by Django 5.0.4 on 2024-05-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_specifiedproblem_style_specifiedproblem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcategory',
            name='simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simulator'),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.validator'),
        ),
    ]
