# Generated by Django 5.0.4 on 2024-05-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_submission_problem_submission_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
