# Generated by Django 5.0.4 on 2024-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_problem_id_submission_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problem_id',
        ),
        migrations.AlterField(
            model_name='specifiedproblem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
