# Generated by Django 5.0.4 on 2024-05-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_problem_submission_problem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.specifiedproblem'),
            preserve_default=False,
        ),
    ]
