# Generated by Django 5.0.4 on 2024-05-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_evualuation_settings_specifiedproblem_evaluation_settings'),
        ('api', '0019_alter_submission_problem_id'),
    ]

    operations = [
    ]
