# Generated by Django 5.0.4 on 2024-05-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20240523_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenchmarkSet',
            new_name='BenchmarkRelations',
        ),
        migrations.RenameModel(
            old_name='EvaluationSetting',
            new_name='EvaluationSettings',
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='Results',
        ),
    ]
