# Generated by Django 5.0.4 on 2024-05-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_results_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmarkrelations',
            options={'verbose_name': 'benchmark relations', 'verbose_name_plural': 'benchmark relations'},
        ),
        migrations.AlterModelOptions(
            name='evaluationsettings',
            options={'verbose_name': 'evaluation settings', 'verbose_name_plural': 'evaluation settings'},
        ),
        migrations.AlterModelOptions(
            name='problemcategory',
            options={'verbose_name': 'problem category', 'verbose_name_plural': 'problem categories'},
        ),
    ]
