# Generated by Django 5.0.4 on 2024-05-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_benchmarkrelations_options_and_more'),
        ('api', '0024_alter_benchmarkset_id_alter_evaluationsetting_id_and_more'),
    ]

    operations = [
    ]
