# Generated by Django 5.0.4 on 2024-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_specifiedproblem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
