# Generated by Django 5.0.4 on 2024-05-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_submission_is_downloadable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problem_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='name',
            new_name='submission_name',
        ),
    ]
