# Generated by Django 5.0.4 on 2024-05-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_evaluationsettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='category',
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='specified_problems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specifiedproblem'),
        ),
    ]
