# Generated by Django 5.0.4 on 2024-05-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_specifiedproblem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcategory',
            name='specified_problems',
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problemcategory'),
        ),
    ]
