# Generated by Django 5.0.4 on 2024-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_problemcategory_specified_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='style',
        ),
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='type',
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='style',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
