# Generated by Django 5.0.4 on 2024-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_specifiedproblem_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationsettings',
            name='name',
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='name',
            field=models.CharField(default='unnamed', max_length=256),
        ),
    ]
