# Generated by Django 5.0.4 on 2024-06-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_evaluationsettings_name_specifiedproblem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifiedproblem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specified_problems', to='api.problemcategory'),
        ),
    ]
