# Generated by Django 5.0.4 on 2024-06-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_problem_submission_problem_id_and_more'),
        ('api', '0032_alter_specifiedproblem_category'),
    ]

    operations = [
    ]
