# Generated by Django 5.0.4 on 2024-06-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20240605_0952'),
        ('api', '0033_merge_20240605_1018'),
    ]

    operations = [
    ]
