# Generated by Django 5.0.4 on 2024-06-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20240605_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('unit', models.CharField(choices=[('none', ''), ('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='none', max_length=4)),
                ('order', models.IntegerField(choices=[(0, 'Cost'), (1, 'Reward')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='benchmarkrelations',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='benchmarkrelations',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_name',
        ),
        migrations.AddField(
            model_name='result',
            name='benchmark_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.benchmarkinstance'),
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='benchmark_instances',
            field=models.ManyToManyField(to='api.benchmarkinstance'),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='unnamed', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.simulator'),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='style',
            field=models.IntegerField(choices=[(0, 'Competition'), (1, 'Scientific')], default=1),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='type',
            field=models.IntegerField(choices=[(0, 'Static'), (1, 'Dynamic')], default=0),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.validator'),
        ),
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='metrics',
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='scoring_metric',
            field=models.ForeignKey(default='run_time', on_delete=django.db.models.deletion.PROTECT, related_name='specifiedproblem_ranking_set', to='api.metric'),
        ),
        migrations.AlterField(
            model_name='result',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric'),
        ),
        migrations.DeleteModel(
            name='BenchmarkRelations',
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='metrics',
            field=models.ManyToManyField(to='api.metric'),
        ),
    ]
