# Generated by Django 5.0.4 on 2024-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_metric_remove_benchmarkrelations_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'None'), ('s', 'Seconds'), ('min', 'Minutes'), ('h', 'Hours')], default='', max_length=4),
        ),
    ]
