# Generated by Django 5.0.4 on 2024-06-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_metric_remove_benchmarkrelations_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='scoring_metrics',
        ),
        migrations.AlterField(
            model_name='metric',
            name='order',
            field=models.IntegerField(choices=[(0, 'Cost'), (1, 'Reward')], default=0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(choices=[('none', ''), ('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='none', max_length=4),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='style',
            field=models.IntegerField(choices=[(0, 'Competition'), (1, 'Scientific')], default=1),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='type',
            field=models.IntegerField(choices=[(0, 'Static'), (1, 'Dynamic')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='ProblemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('scoring_metric', models.BooleanField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
                ('specified_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specifiedproblem')),
            ],
        ),
        migrations.RemoveField(
            model_name='specifiedproblem',
            name='metrics'
        ),
        migrations.AddField(
            model_name='specifiedproblem',
            name='metrics',
            field=models.ManyToManyField(related_name='specified_problems', through='api.ProblemMetric', to='api.metric'),
        ),
    ]
