# Generated by Django 5.0.4 on 2024-06-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20240605_1043'),
        ('api', '0035_alter_result_benchmark_instance'),
    ]

    operations = [
    ]
