# Generated by Django 5.0.4 on 2024-06-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_specifiedproblem_scoring_metrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemmetric',
            old_name='specified_problem',
            new_name='problem',
        ),
    ]
