# Generated by Django 5.0.4 on 2024-06-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_metric_order_alter_problemcategory_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(choices=[('none', ''), ('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='none', max_length=4),
        ),
        migrations.AlterField(
            model_name='specifiedproblem',
            name='metrics',
            field=models.ManyToManyField(related_name='problem_metris+', to='api.metric'),
        ),
        migrations.AlterField(
            model_name='specifiedproblem',
            name='scoring_metrics',
            field=models.ManyToManyField(related_name='problem_scoring_metrics+', to='api.metric'),
        ),
    ]
