# Generated by Django 5.0.4 on 2024-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_metric_unit_alter_specifiedproblem_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifiedproblem',
            name='metrics',
            field=models.ManyToManyField(related_name='problem_metrics+', to='api.metric'),
        ),
    ]
