name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run at most 1 job at a time per PR/branch
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Grand MySQL user privilages
      run:
        mysql -h 127.0.0.1 -u root -prootpassword -e "GRANT ALL PRIVILEGES ON test_db.* TO 'testuser'@'%';"
    - name: Run Tests
      env:
        DB_NAME: "db"
        DB_HOST: 127.0.0.1
        DB_USER: "testuser"
        DB_PASSWORD: "testpassword"
        SECRET_KEY: "test"
        FRONTEND_URL: "http://localhost:5173"
        ALLOWED_HOSTS: "*"
        CSRF_TRUSTED_ORIGINS: "http://localhost"
        AZURE_STORAGE_CONTAINER_SUBMISSION: "submissions"
      run: |
        cd backend
        coverage run --source='.' manage.py test tests
        coverage report
